[workspace]
authors = ["Chang Shao Hsuan <brianchang4591@gmail.com>"]
name = "pixi_panda_ros2_ITR"
version = "0.1.0"
channels = ["conda-forge"]
platforms = ["linux-64"]

[activation]
scripts = ["scripts/set_ros_env.sh", "scripts/set_hardware_env.sh", "install/setup.bash"]

[dependencies]
python = "*"
compilers = "*"
cmake = "*"
pkg-config = "*"
make = "*"
ninja = "*"
requests = ">=2.32.4,<3"
websockets = ">=15.0.1,<16"
numpy = "<=2.3"
opencv = "*"
pandas = ">=2.3.0,<3"
pyarrow = ">=20.0.0,<21"

[target.linux.dependencies]
libgl-devel = "*"


[environments]
jazzy = { features = ["jazzy", "dev"] }
jazzy-realsense = { features = ["jazzy", "dev", "realsense-src"] }

# ROS2 Jazzy Feature
[feature.jazzy]
channels = ["https://prefix.dev/robostack-jazzy"]

[feature.jazzy.dependencies]
colcon-common-extensions = "*"
pinocchio = ">=3.4.0,<4"
poco = "<1.13.0"

ros-jazzy-desktop = "*"
ros-jazzy-joint-state-publisher = ">=2.4.0,<3"
ros-jazzy-rmw-cyclonedds-cpp = "*"
ros-jazzy-ros2-control = "*"
ros-jazzy-ros2-controllers = "*"
ros-jazzy-xacro = ">=2.0.13,<3"
ros-jazzy-generate-parameter-library = "*"
rosdep = "*"
ros-jazzy-topic-tools = ">=1.3.3,<2"
ros-jazzy-topic-tools-interfaces = ">=1.3.3,<2"
ros-jazzy-image-transport-plugins = "*"
# NOTE:
# Do not add `ros-jazzy-realsense2-camera` binary package here on this host.
# Current available builds require newer glibc than this system provides.
# Use the `jazzy-realsense` environment with source build workflow below.

[feature.jazzy.tasks]
update-submodules = "git submodule update --init --recursive"
build = "colcon build --cmake-args -DCMAKE_BUILD_TYPE=Release -DBUILD_TESTING=OFF -DBUILD_TESTS=OFF -DBUILD_EXAMPLES=OFF -DCMAKE_POLICY_VERSION_MINIMUM=3.5 -Wno-dev --symlink-install"
setup = { depends-on = ["update-submodules",  "build"] }
franka = "ros2 launch franka_bringup franka.launch.py"
franka_platform = "ros2 launch franka_bringup franka_platform.launch.py"
franka_button = "ros2 launch franka_buttons button_to_record_msg.launch.py"

[feature.realsense-src.tasks]
fetch-realsense-ros = "test -d src/realsense-ros || git clone https://github.com/IntelRealSense/realsense-ros.git src/realsense-ros"
pin-realsense-ros = "git -C src/realsense-ros fetch --tags && git -C src/realsense-ros reset --hard HEAD && git -C src/realsense-ros clean -fd && git -C src/realsense-ros checkout 4.56.4"
setup-realsense = { depends-on = ["fetch-realsense-ros", "pin-realsense-ros", "setup"] }

[feature.realsense-src.dependencies]
librealsense = "*"

# Development tools
[feature.dev.pypi-dependencies]
ruff = "*"
pytest = "*"
crisp-python = { git = "https://github.com/brianchang1025/crisp_py_panda"}
rich = "*"

[pypi-dependencies]
filelock = ">=3.20.3, <4"
python-dotenv = ">=1,<2"