#!/usr/bin/env bash

export THIRD_PERSON_CAMERA_SN="_827112070588"
export WRIST_CAMERA_SN="_827112070502"
export FRANKA_IP_LEFT="192.168.31.10"
export FRANKA_IP_RIGHT="192.168.32.10"
export FRANKA_DESK_USERNAME="admin"
export FRANKA_DESK_PASSWORD="pandapanda"
# export FRANKA_DESK_USERNAME_LEFT="admin"
# export FRANKA_DESK_PASSWORD_LEFT="pandapanda"
# export FRANKA_DESK_USERNAME_RIGHT="admin"
# export FRANKA_DESK_PASSWORD_RIGHT="pandapanda"
